version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.27.0
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 100
      GRID_TIMEOUT: 100

  chrome-node-1:
    image: selenium/node-chrome:131.0
    # shm_size: 2gb #shared Memory
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900

  chrome-node-2:
    image: selenium/node-chrome:131.0
    # shm_size: 2gb // shared Memory
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5903:5900

  firefox:
    image: selenium/node-firefox:133.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - 5904:5900

  edge:
    image: selenium/node-edge:4.0.0-rc-2-20210930
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - 5905:5900

